config/routes.rb
Bookshelf::Application.routes.draw do
  get "users/index"

  devise_for :users

  root :to => 'index#index'
  scope "/master" do
    resources :books
    resources :shelves 
  end
  scope "/admin" do
    resources :users
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :description, :name, :volume, :shelf_id
  belongs_to :shelf
  scope :latest_by_shelf, lambda {|id|
    @result = []
    h = where('shelf_id = :sid', :sid => "#{id}").group("books.name").maximum(:volume)
    h.each_pair {|key, value|
      @result.push(find_by_name_and_volume(key, value))
    }
    return @result
  }
  scope :latest, lambda {
    @result = []
    h = group("books.name").maximum(:volume)
    h.each_pair {|key, value|
      @result.push(find_by_name_and_volume(key, value))
    }
    return @result
  }
end

app/models/book_search_form.rb
class BookSearchForm
  extend ActiveModel::Naming  
  include ActiveModel::Conversion  
  
  attr_accessor :shelf_id, :latest
  
  def initialize(params)
    self.shelf_id = params[:shelf_id] if params
    self.latest = params[:latest] if params
  end
  
  def persisted?
    false
  end
end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :books
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @shelves = Shelf.all
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @shelves = Shelf.all
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @book_search_form = BookSearchForm.new params[:book_search_form]
    @shelves = Shelf.all
    if @book_search_form.shelf_id.blank? then
      logger.error '================='
      #key = @shelves[0].id
      #@books = Book.where(:shelf_id => key)
      if @book_search_form.latest == "1" then
        @books = Book.latest
      else
        @books = Book.all
      end
    else
      key = @book_search_form.shelf_id
      if @book_search_form.latest == "1" then
        #@books = []
        #h = Book.where('shelf_id = :sid', :sid => "#{key}").group("books.name").maximum(:volume)
        #@books = @books.latest_by_shelf(key)
        #h.each_pair {|key, value|
        #  @books.push(Book.find_by_name_and_volume(key, value))
        #}
        @books = Book.latest_by_shelf(key)
      else
        @books = Book.where(:shelf_id => key)
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shelves }
    end
  end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  before_filter :authenticate_user!

  # GET /shelves
  # GET /shelves.json
  def index
    #@shelves = Shelf.all
    @shelves = Shelf.paginate(:page => params[:page], :order => 'created_at desc', :per_page => 2)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shelves }
    end
  end

  # GET /shelves/1
  # GET /shelves/1.json
  def show
    @shelf = Shelf.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shelf }
    end
  end

  # GET /shelves/new
  # GET /shelves/new.json
  def new
    @shelf = Shelf.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shelf }
    end
  end

  # GET /shelves/1/edit
  def edit
    @shelf = Shelf.find(params[:id])
  end

  # POST /shelves
  # POST /shelves.json
  def create
    @shelf = Shelf.new(params[:shelf])

    respond_to do |format|
      if @shelf.save
        format.html { redirect_to @shelf, notice: 'Shelf was successfully created.' }
        format.json { render json: @shelf, status: :created, location: @shelf }
      else
        format.html { render action: "new" }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shelves/1
  # PUT /shelves/1.json
  def update
    @shelf = Shelf.find(params[:id])

    respond_to do |format|
      if @shelf.update_attributes(params[:shelf])
        format.html { redirect_to @shelf, notice: 'Shelf was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shelves/1
  # DELETE /shelves/1.json
  def destroy
    @shelf = Shelf.find(params[:id])
    @shelf.destroy

    respond_to do |format|
      format.html { redirect_to shelves_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= collection_select(:book, :shelf_id, @shelves, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.number_field :volume %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h2>Listing books</h2>
<p>
<table>
  <tr>
    <th>Name</th>
    <th>Volume</th>
    <th>Description</th>
    <th>Shelf</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</p>
<% @books.each do |book| %>
  <tr>
    <td><%= book.name %></td>
    <td><%= book.volume %></td>
    <td><%= book.description %></td>
    <td><%= book.shelf.name%></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @book.name %>
</p>

<p>
  <b>Volume:</b>
  <%= @book.volume %>
</p>

<p>
  <b>Description:</b>
  <%= @book.description %>
</p>

<p>
  <b>Shelf:</b>
  <%= @book.shelf.name%>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/index/index.html.erb
<h1>Bookshelf</h1>

<%= form_for(
  @book_search_form,
  :url => {:action => :index},
  :html => {:method => :get}) do |f| %>
  <%#= select_tag 'shelf_id', options_from_collection_for_select(@shelves, :id, :name) %>
  <%= f.select :shelf_id, @shelves.map{|i| [i.name, i.id]}, {:include_blank => true} %>
  <%= f.check_box :latest %>最新刊
  <%= f.submit 'Search' %>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Volume</th>
    <th>Description</th>
  </tr>
  <% @books.each do |book| %> 
  <tr>
    <th><%= book.name %></th>
    <th><%= book.volume%></th>
    <th><%= book.description%></th>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Bookshelf</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <hgroup>
      <h1>Bookshelf</h1>
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
      <%= link_to 'User Info', edit_user_registration_path, :method => :get%>
    </hgroup>
    <nav>
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/master/shelves">Shelf</a></li>
        <li><a href="/master/books">Book</a></li>
        <li><a href="/admin/users">User</a></li>
      </ul>
    </nav> 
  </header>
  <div id="contents">
    <div id="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
  <footer>
    <p>2013&copy;chiroru_0130@yahoo.co.jp</p>
  </footer>
</body>
</html>

app/views/shelves/_form.html.erb
<%= form_for(@shelf) do |f| %>
  <% if @shelf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shelf.errors.count, "error") %> prohibited this shelf from being saved:</h2>

      <ul>
      <% @shelf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shelves/edit.html.erb
<h1>Editing shelf</h1>

<%= render 'form' %>

<%= link_to 'Show', @shelf %> |
<%= link_to 'Back', shelves_path %>

app/views/shelves/index.html.erb
<h2>Listing shelves</h2>
<p>
Total <%=h @shelves.total_entries %>
Total Page <%=h @shelves.total_pages %>
Current Page <%=h @shelves.current_page%>
<%= will_paginate @shelves %>
</p>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @shelves.each do |shelf| %>
  <tr>
    <td><%= shelf.name %></td>
    <td><%= shelf.description %></td>
    <td><%= link_to t("label.show"), shelf %></td>
    <td><%= link_to t("label.edit"), edit_shelf_path(shelf) %></td>
    <td><%= link_to t("label.remove"), shelf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @shelves %>
<br />
<%= link_to t("label.add"), new_shelf_path %>

app/views/shelves/new.html.erb
<h1>New shelf</h1>

<%= render 'form' %>

<%= link_to 'Back', shelves_path %>

app/views/shelves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shelf.name %>
</p>

<p>
  <b>Description:</b>
  <%= @shelf.description %>
</p>


<%= link_to 'Edit', edit_shelf_path(@shelf) %> |
<%= link_to 'Back', shelves_path %>

app/views/users/index.html.erb
<h2>Listing users</h2>

<table>
  <tr>
     <th>ID</th>
     <th>Mail</th>
     <th>Edit</th>
     <th>Destroy</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.id%></td>
    <td><%= user.email %></td>
    <td><%= link_to "edit", edit_user_registration_path(user.id) %></td>
    <td><%= link_to "destroy", user, method: :delete %></td>
  </tr>
  <% end %>
</table>